# .github/workflows/ssh_deploy.yml

name: Deploy Team Webpage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - uses: actions/checkout@master

      # Copying files and artifacts via SSH
      - name: Copying files to server
        uses: nogsantos/scp-deploy@master
        with:
          src: ./dist/*
          host: ${{ secrets.CONN_NAME }}
          remote: '/var/www/team18/'
          port: 22
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
